# Generated by Django 5.2.7 on 2026-01-28 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_weeklysubjectgoal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="difficulty",
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_subject_per_user"
            ),
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
    ]
