# Generated by Django 5.2.7 on 2026-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_conversation_summary_conversation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialchunk",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
