# Generated by Django 5.2.7 on 2026-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_conversationmemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="mode",
            field=models.CharField(
                choices=[
                    ("CHAT", "Chat"),
                    ("FLASHCARD", "Flashcard"),
                    ("QUIZ", "Quiz"),
                ],
                default="CHAT",
                max_length=20,
            ),
        ),
    ]
